version: '3'
services:
  rabbit-server-01:
    image: "rabbitmq:3-management"
    container_name: rabbit-server-01
    hostname: "rabbit-server-1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "25672:25672"
    labels:
      NAME: "rabbit-server-1"
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"